package ch.bfh.bti7081.s2016.purple.HealthVisitor.data;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;
import java.util.Date;

/**
 * Created by tgdflto1 on 21/05/16.
 *
 * This class has single table inheritance because not all persons have the same attributes
 *
 * https://wiki.eclipse.org/EclipseLink/Examples/JPA/Inheritance
 */

@Entity
@Table(name="PERSON")
@Inheritance(strategy= InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="TYPE", discriminatorType=DiscriminatorType.STRING,length=20)
@DiscriminatorValue("P")
public class PersonEntity {
    @Id
    private int id;

    private String firstName;
    private String lastName;
    private String password;
    private String email;
    private Date dateOfBirth;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


}
